services:
  api:
    container_name: url-shortener-api-dev
    build:
      context: .
      target: dev
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.development
    depends_on:
      - postgres
    restart: unless-stopped
    # Volumes to hot reload
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./entrypoint.sh:/app/entrypoint.sh:cached
      - /app/node_modules
    entrypoint: ["sh", "/app/entrypoint.sh"]
    command: ["pnpm", "start:dev"]
    networks:
      - app-network-dev

  postgres:
    container_name: url-shortener-db-dev
    image: bitnami/postgresql
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - app-network-dev

volumes:
  pgdata-dev:

networks:
  app-network-dev:
    driver: bridge